// produtos.js
const produtos = [
    { id: 1, nome: "Spider-Man 2", preco: 299.00, imagem: "imgs/marvels-spider-man.jpeg", plataforma: "PlayStation 5 / PC", genero: "Ação, Aventura", lancamento: "2023", classificacao: "+16 anos", descricao: "Spider-Man 2 traz Peter Parker e Miles Morales enfrentando novos vilões como Venom e Kraven.", desenvolvedora: "Insomniac Games", distribuidora: "Sony Interactive", modos: "Single player", idiomas: "Português, Inglês" },
    { id: 2, nome: "GTA VI", preco: 499.90, imagem: "imgs/Grand_Theft_VI.png", plataforma: "PlayStation 5 / Xbox Series X", genero: "Ação, Mundo Aberto", lancamento: "2026", classificacao: "+18 anos", descricao: "Retorne a Vice City com uma história envolvente e gráficos de última geração.", desenvolvedora: "Rockstar Games", distribuidora: "Rockstar Games", modos: "Single player, Multiplayer", idiomas: "Português, Inglês" },
    { id: 3, nome: "Batman Arkham", preco: 89.90, imagem: "imgs/Batman_Arkham.jpg", plataforma: "PC / PlayStation / Xbox", genero: "Ação", lancamento: "2011", classificacao: "+14 anos", descricao: "Explore os segredos mais sombrios e enfrente vilões icônicos em Arkham City.", desenvolvedora: "Rocksteady", distribuidora: "Warner Bros", modos: "Single player", idiomas: "Português, Inglês" },
    { id: 4, nome: "Elden Ring", preco: 249.00, imagem: "imgs/Elden_Ring.jpg", plataforma: "PC / PS5 / Xbox", genero: "RPG, Soulslike", lancamento: "2022", classificacao: "+16 anos", descricao: "Desvende os mistérios das Terras Intermédias neste RPG desafiador aclamado pela crítica.", desenvolvedora: "FromSoftware", distribuidora: "Bandai Namco", modos: "Single player, Coop", idiomas: "Português, Inglês" },
    { id: 5, nome: "God of War", preco: 199.00, imagem: "imgs/god_of_war.png", plataforma: "PlayStation / PC", genero: "Ação, Aventura", lancamento: "2018", classificacao: "+18 anos", descricao: "Kratos e Atreus em uma jornada mística pelos reinos da mitologia nórdica.", desenvolvedora: "Santa Monica Studio", distribuidora: "Sony Interactive", modos: "Single player", idiomas: "Português, Inglês" },
    { id: 6, nome: "FC 25 (FIFA)", preco: 350.00, imagem: "imgs/fifa 2025.jpg", plataforma: "Multiplataforma", genero: "Esporte", lancamento: "2024", classificacao: "Livre", descricao: "O simulador de futebol mais realista do mundo com os principais campeonatos mundiais.", desenvolvedora: "EA Sports", distribuidora: "EA Sports", modos: "Single player, Multiplayer", idiomas: "Português, Inglês" },
    { id: 7, nome: "Mortal Kombat 1", preco: 270.00, imagem: "imgs/Mortal_Kombat_1_.png", plataforma: "Multiplataforma", genero: "Luta", lancamento: "2023", classificacao: "+18 anos", descricao: "Um universo de luta inteiramente renascido criado pelo Deus do Fogo Liu Kang.", desenvolvedora: "NetherRealm Studios", distribuidora: "Warner Bros", modos: "Single player, Multiplayer", idiomas: "Português, Inglês" },
    { id: 8, nome: "Resident Evil 4", preco: 150.00, imagem: "imgs/resident-evil-4.jpg", plataforma: "Multiplataforma", genero: "Terror, Ação", lancamento: "2023", classificacao: "+18 anos", descricao: "A sobrevivência é apenas o começo neste remake espetacular do clássico de sobrevivência.", desenvolvedora: "Capcom", distribuidora: "Capcom", modos: "Single player", idiomas: "Português, Inglês" }
];